{
  parserClass="com.kodeir.plugin.cls.parser.SimpleParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="com.kodeir.plugin.cls.psi"
  psiImplPackage="com.kodeir.plugin.cls.psi.impl"

  elementTypeHolderClass="com.kodeir.plugin.cls.psi.SimpleTypes"
  elementTypeClass="com.kodeir.plugin.cls.psi.SimpleElementType"
  tokenTypeClass="com.kodeir.plugin.cls.psi.SimpleTokenType"

  /*psiImplUtilClass="com.kodeir.plugin.cls.psi.impl.SimplePsiImplUtil"*/
}

/*
simpleFile ::= (property|COMMENT)*


property ::= (KEY SEPARATOR VALUE?)|KEY {
    pin=3
    recoverWhile="recover_property"
    mixin="com.kodeir.plugin.cls.psi.impl.SimpleNamedElementImpl"
    implements="com.kodeir.plugin.cls.psi.SimpleNamedElement"
    methods=[getKey getValue getName setName getNameIdentifier getPresentation]
}
 */

simpleFile ::= item_*


private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY